application: geoyoutube-1290
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: search.html
  upload: search.html
  
- url: /search.html
  static_files: search.html
  upload: search.html
  
- url: /about.html
  static_files: about.html
  upload: about.html
  
- url: /css
  static_dir: css
  
- url: /js
  static_dir: js

- url: /images
  static_dir: images
  
- url: /view.html
  static_files: view.html
  upload: view.html

- url: /privacypolicy.htm
  static_files: privacypolicy.htm
  upload: privacypolicy.htm
  
- url: /terms.htm
  static_files: terms.htm
  upload: terms.htm  
  
- url: /redirect.html
  static_files: redirect.html
  upload: redirect.html
